$(document).ready(function(){
	$(".contact-button").mouseenter(function(){
		$(".jake").show();
		$(".kenshin").show();
	})
	.mouseleave(function(){
		$(".jake").hide();
		$(".kenshin").hide();
	})
});